#!/usr/bin/env bash

# If no site name is passed assume the directory is the site name
if [ -z "$1" ]
  then
    set -- ${PWD##*/}
fi

sudo chmod -R u+x ./*

if [ -d .docker/config/sites-available ]; then  
  if [ ! -e .docker/config/sites-available/$1.conf ]; then
    # Create Conf file for site
    touch .docker/config/sites-available/$1.conf

    # Add additional 443 fields 

    echo "<VirtualHost *:80>" >> .docker/config/sites-available/$1.conf
    echo "ServerAdmin admin@yourdomain.com" >> .docker/config/sites-available/$1.conf
    echo "DocumentRoot /var/www/html/" >> .docker/config/sites-available/$1.conf
    echo "ServerName $1" >> .docker/config/sites-available/$1.conf
    echo "ServerAlias www.$1" >> .docker/config/sites-available/$1.conf
    echo "<Directory /var/www/html/>" >> .docker/config/sites-available/$1.conf
    echo "    Options FollowSymLinks" >> .docker/config/sites-available/$1.conf
    echo "    AllowOverride All" >> .docker/config/sites-available/$1.conf
    echo "    Order allow,deny" >> .docker/config/sites-available/$1.conf
    echo "    allow from all" >> .docker/config/sites-available/$1.conf
    echo "</Directory>" >> .docker/config/sites-available/$1.conf
    echo "</VirtualHost>" >> .docker/config/sites-available/$1.conf
    echo "<VirtualHost *:443>" >> .docker/config/sites-available/$1.conf
    echo "ServerName $1" >> .docker/config/sites-available/$1.conf
    echo "SSLEngine on" >> .docker/config/sites-available/$1.conf
    echo "SSLCertificateFile /etc/apache2/ssl/$1.crt" >> .docker/config/sites-available/$1.conf
    echo "SSLCertificateKeyFile /etc/apache2/ssl/$1.key" >> .docker/config/sites-available/$1.conf
    echo "DocumentRoot /var/www/html/" >> .docker/config/sites-available/$1.conf
    echo "</VirtualHost>" >> .docker/config/sites-available/$1.conf
  fi
fi


docker image pull cschrum/onebox-m2:7.0

if [ "$(uname)" == "Darwin" ]; then
    git checkout -f mac;
    sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
    && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml;
elif [ "$(uname)" == "cygwin" ] || [ "$(uname)" == "msys" ] || [ "$(uname)" == "win32" ]; then
    git checkout -f windows;
    sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
    && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml;
else
    #git checkout -f master;
    sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;
fi

if [ ! -e src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

if [ -d src/app/etc ]; then  
  if [ ! -e src/app/etc/env.php ]; then
    cp .docker/users/env.sample.php src/app/etc/env.php;
  fi
fi

# Create SSL
openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj \
    "/C=US/ST=Missouri/L=Springfield/O=Nucleus/CN=$1" \
    -keyout .docker/config/$1.key -out .docker/config/$1.crt


chmod -R 777 src

bash start