#!/usr/bin/env bash
docker-compose up -d
echo "
/////////////////////////////////////////////////////
      Created by Curtis Schrum
      Thanks to Rafael Corrêa Gomes
      
      Remember to add your new site to /etc/hosts 127.0.0.1 domain
      Access your new links:
      🌎 Web server: domain.local

      Emails served by MailHog
      ✉️ Local emails: http://localhost:8025
////////////////////////////////////////////////////"